// Sports
export const SPORTS = {
  run: {
    label: "Run",
    icon: "🏃",
    color: "#22c55e",
    unit: "mi",
    metricLabel: "Distance",
  },
  cycle: {
    label: "Cycle",
    icon: "🚴",
    color: "#555",
    unit: "mi",
    metricLabel: "Distance",
  },
  swim: {
    label: "Swim",
    icon: "🏊",
    color: "#06b6d4",
    unit: "yd",
    metricLabel: "Distance",
  },
  lift: {
    label: "Lift",
    icon: "🏋️",
    color: "#f59e0b",
    unit: "lbs",
    metricLabel: "Volume",
  },
};

// Level system
export const LEVELS = [
  { level: 1, title: "Rookie", minXP: 0, maxXP: 500 },
  { level: 2, title: "Contender", minXP: 500, maxXP: 1200 },
  { level: 3, title: "Athlete", minXP: 1200, maxXP: 2500 },
  { level: 4, title: "Competitor", minXP: 2500, maxXP: 4500 },
  { level: 5, title: "Performer", minXP: 4500, maxXP: 7500 },
  { level: 6, title: "Champion", minXP: 7500, maxXP: 12000 },
  { level: 7, title: "Elite", minXP: 12000, maxXP: 18000 },
  { level: 8, title: "Master", minXP: 18000, maxXP: 26000 },
  { level: 9, title: "Legend", minXP: 26000, maxXP: 36000 },
  { level: 10, title: "Immortal", minXP: 36000, maxXP: Infinity },
];

// Achievement definitions
export const ACHIEVEMENT_DEFS = [
  {
    id: "first_workout",
    name: "First Step",
    icon: "👟",
    description: "Log your first workout",
    xpReward: 50,
    requirementType: "workouts",
    requirementValue: 1,
  },
  {
    id: "workouts_10",
    name: "Getting Started",
    icon: "🔥",
    description: "Complete 10 workouts",
    xpReward: 100,
    requirementType: "workouts",
    requirementValue: 10,
  },
  {
    id: "workouts_50",
    name: "Dedicated",
    icon: "💪",
    description: "Complete 50 workouts",
    xpReward: 300,
    requirementType: "workouts",
    requirementValue: 50,
  },
  {
    id: "workouts_100",
    name: "Century Club",
    icon: "💯",
    description: "Complete 100 workouts",
    xpReward: 750,
    requirementType: "workouts",
    requirementValue: 100,
  },
  {
    id: "streak_3",
    name: "On a Roll",
    icon: "🎯",
    description: "3-day active streak",
    xpReward: 75,
    requirementType: "streak",
    requirementValue: 3,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    icon: "📅",
    description: "7-day active streak",
    xpReward: 200,
    requirementType: "streak",
    requirementValue: 7,
  },
  {
    id: "streak_30",
    name: "Iron Will",
    icon: "🛡️",
    description: "30-day active streak",
    xpReward: 1000,
    requirementType: "streak",
    requirementValue: 30,
  },
  {
    id: "distance_5k",
    name: "First 5K",
    icon: "🏅",
    description: "Run 5 kilometers",
    xpReward: 100,
    requirementType: "distance",
    requirementValue: 3.1,
    sport: "run",
  },
  {
    id: "distance_10k",
    name: "10K Club",
    icon: "🥈",
    description: "Run 10 kilometers",
    xpReward: 200,
    requirementType: "distance",
    requirementValue: 6.2,
    sport: "run",
  },
  {
    id: "distance_half",
    name: "Half Marathoner",
    icon: "🥇",
    description: "Run a half marathon",
    xpReward: 500,
    requirementType: "distance",
    requirementValue: 13.1,
    sport: "run",
  },
  {
    id: "distance_100mi",
    name: "Century Rider",
    icon: "🚵",
    description: "Cycle 100 miles total",
    xpReward: 400,
    requirementType: "total_distance",
    requirementValue: 100,
    sport: "cycle",
  },
  {
    id: "volume_10k",
    name: "Iron Lifter",
    icon: "⚡",
    description: "Lift 10,000 lbs total volume",
    xpReward: 200,
    requirementType: "total_volume",
    requirementValue: 10000,
  },
  {
    id: "volume_100k",
    name: "Powerhouse",
    icon: "🏆",
    description: "Lift 100,000 lbs total volume",
    xpReward: 750,
    requirementType: "total_volume",
    requirementValue: 100000,
  },
  {
    id: "xp_1000",
    name: "XP Hunter",
    icon: "⭐",
    description: "Earn 1,000 XP",
    xpReward: 0,
    requirementType: "xp",
    requirementValue: 1000,
  },
  {
    id: "xp_5000",
    name: "XP Master",
    icon: "🌟",
    description: "Earn 5,000 XP",
    xpReward: 0,
    requirementType: "xp",
    requirementValue: 5000,
  },
];

// Daily quests pool
export const QUEST_POOL = [
  {
    id: "q_run_3mi",
    sport: "run",
    label: "Run 3 miles",
    target: 3,
    unit: "mi",
    xpReward: 75,
  },
  {
    id: "q_run_5mi",
    sport: "run",
    label: "Run 5 miles",
    target: 5,
    unit: "mi",
    xpReward: 120,
  },
  {
    id: "q_cycle_10mi",
    sport: "cycle",
    label: "Cycle 10 miles",
    target: 10,
    unit: "mi",
    xpReward: 80,
  },
  {
    id: "q_cycle_30min",
    sport: "cycle",
    label: "Cycle for 30 minutes",
    target: 30,
    unit: "min",
    xpReward: 60,
  },
  {
    id: "q_swim_1000",
    sport: "swim",
    label: "Swim 1,000 yards",
    target: 1000,
    unit: "yd",
    xpReward: 90,
  },
  {
    id: "q_lift_5sets",
    sport: "lift",
    label: "Complete 5 sets",
    target: 5,
    unit: "sets",
    xpReward: 65,
  },
  {
    id: "q_lift_30min",
    sport: "lift",
    label: "Lift for 30 minutes",
    target: 30,
    unit: "min",
    xpReward: 60,
  },
  {
    id: "q_any_workout",
    sport: null,
    label: "Complete any workout",
    target: 1,
    unit: "workout",
    xpReward: 50,
  },
];

// Leaderboard mock users
export const LEADERBOARD_USERS = [
  {
    id: "u1",
    name: "Alex Chen",
    username: "alexc",
    avatar: null,
    xp: 18450,
    level: 7,
    weeklyDistance: 42.3,
    monthlyVolume: 125000,
    streak: 21,
  },
  {
    id: "u2",
    name: "Jordan Smith",
    username: "jsmith",
    avatar: null,
    xp: 15200,
    level: 7,
    weeklyDistance: 38.1,
    monthlyVolume: 98000,
    streak: 14,
  },
  {
    id: "u3",
    name: "Sam Rivera",
    username: "samr",
    avatar: null,
    xp: 12800,
    level: 6,
    weeklyDistance: 31.5,
    monthlyVolume: 87000,
    streak: 9,
  },
  {
    id: "u4",
    name: "Taylor Kim",
    username: "tkim",
    avatar: null,
    xp: 9600,
    level: 5,
    weeklyDistance: 28.0,
    monthlyVolume: 72000,
    streak: 7,
  },
  {
    id: "u5",
    name: "Morgan Lee",
    username: "mlee",
    avatar: null,
    xp: 7200,
    level: 5,
    weeklyDistance: 22.4,
    monthlyVolume: 61000,
    streak: 5,
  },
  {
    id: "u6",
    name: "Casey Park",
    username: "cpark",
    avatar: null,
    xp: 5800,
    level: 4,
    weeklyDistance: 18.7,
    monthlyVolume: 54000,
    streak: 4,
  },
  {
    id: "u7",
    name: "Riley Johnson",
    username: "rjohnson",
    avatar: null,
    xp: 4100,
    level: 4,
    weeklyDistance: 15.2,
    monthlyVolume: 43000,
    streak: 3,
  },
  {
    id: "u8",
    name: "Drew Martinez",
    username: "dmartinez",
    avatar: null,
    xp: 2900,
    level: 3,
    weeklyDistance: 12.0,
    monthlyVolume: 31000,
    streak: 2,
  },
];
