/**
 * Centralized user-facing copy (en). Ready for i18n: replace with t(key) or locale-based lookup.
 * @see COPY_AUDIT.md
 */
export const COPY = {
  // ── Common ─────────────────────────────────────────────────────────────
  loading: 'Loading…',
  cancel: 'Cancel',
  done: 'Done',
  share: 'Share',
  retry: 'Retry',
  dismissNotification: 'Dismiss notification',
  skipToMain: 'Skip to main content',
  linkCopied: 'Link copied',
  logOut: 'Log out',
  logout: 'Logout',
  toggleTheme: 'Toggle theme',
  switchToLightTheme: 'Switch to light theme',
  switchToDarkTheme: 'Switch to dark theme',
  goToProfile: 'Go to profile',
  zenith: 'Zenith',
  syncingWithCloud: 'Syncing with cloud…',

  // ── Nav ────────────────────────────────────────────────────────────────
  navDashboard: 'Dashboard',
  navActivities: 'Activities',
  navProgress: 'Progress',
  navChallenges: 'Challenges',
  navLeaderboard: 'Leaderboard',
  navProfile: 'Profile',
  navFeed: 'Feed',
  navHome: 'Home',
  navHistory: 'History',
  navWorkout: 'Workout',

  // ── Auth / Login ───────────────────────────────────────────────────────
  authWelcomeBack: 'Welcome Back',
  authLoginSubtitle: 'Log in to your Zenith account',
  authLoginFormLabel: 'Log in form',
  authEmailAddress: 'Email Address',
  authPassword: 'Password',
  authPlaceholderEmail: 'name@example.com',
  authPlaceholderPassword: '••••••••',
  authLoggingIn: 'Logging in…',
  authLogIn: 'Log In',
  authNoAccount: "Don't have an account?",
  authSignUp: 'Sign Up',
  errorLoginTimeout: 'Login timed out. Check your connection and try again.',
  errorIncorrectCredentials: 'Incorrect email or password.',
  errorTooManyAttempts: 'Too many attempts. Please wait a bit and try again.',
  errorLoginGeneric: 'Unable to log in right now. Please try again.',

  // ── Auth / Signup ───────────────────────────────────────────────────────
  authCreateAccount: 'Create Account',
  authSignupSubtitle: 'Join the Zenith fitness community',
  authSignupFormLabel: 'Sign up form',
  authFullName: 'Full Name',
  authConfirmPassword: 'Confirm Password',
  authPlaceholderName: 'John Doe',
  authCreatingAccount: 'Creating account…',
  authSignUpButton: 'Sign Up',
  authHasAccount: 'Already have an account?',
  authLogInLink: 'Log In',
  errorEmailInUse: 'An account with this email already exists. Try logging in instead.',
  errorInvalidEmail: 'Please enter a valid email address.',
  errorWeakPassword: 'Password is too weak. Use at least 6 characters.',
  errorNetwork: 'Could not save; check your connection.',
  errorSignupGeneric: 'Unable to create account right now. Please try again.',
  errorPasswordsNoMatch: 'Passwords do not match.',

  // ── Dashboard ──────────────────────────────────────────────────────────
  dashboardBrand: 'ZENITH',
  dashboardTagline: 'Performance tracking that feels elite',
  dashboardWelcomeBack: 'Welcome back,',
  dashboardDayStreak: 'day streak',
  dashboardTotalXp: 'TOTAL XP',
  dashboardMaxLevel: 'Max level reached',
  dashboardXpToLevel: 'XP to level',
  dashboardWeeklyGoal: 'Weekly goal',
  dashboardTotalWorkouts: 'Total workouts',
  dashboardSessions: 'sessions',
  dashboardQuickStart: 'Quick Start',
  dashboardQuickRun: 'Quick Run',
  dashboardQuickRunDetail: '20 min cardio',
  dashboardStrengthBuilder: 'Strength Builder',
  dashboardStrengthBuilderDetail: '35 min lifting',
  dashboardFullBodyMix: 'Full Body Mix',
  dashboardFullBodyMixDetail: '45 min challenge',
  dashboardWeeklySnapshot: 'Weekly Snapshot',
  dashboardDetails: 'Details',
  dashboardView1RM: 'View 1RM',
  dashboardSessionsLabel: 'Sessions',
  dashboardDistance: 'Distance',
  dashboardVolume: 'Volume',
  dashboardBestStreak: 'Best streak',
  dashboardMiles: 'mi',
  dashboardLbs: 'lbs',
  dashboardDays: 'days',
  dashboardGoalCompletion: 'goal completion',
  dashboardDailyQuests: 'Daily Quests',
  dashboardQuestsSubtitle: 'Complete to earn bonus XP.',
  dashboardQuestsLoading: 'Your daily quests are loading…',
  dashboardQuestsDone: 'quests done',
  dashboardQuestDone: 'Done',
  dashboardRecentAchievements: 'Recent Achievements',
  dashboardViewAll: 'View all',
  dashboardActivityFeed: 'Activity Feed',
  feedTitle: 'Feed',
  feedSubtitle: 'Activities from people you follow',
  feedEmptyTitle: 'No activities yet',
  feedEmptyDesc: 'Follow athletes to see their workouts here.',
  feedFindPeople: 'Find people',
  feedExplore: 'Explore leaderboard',
  feedLoadMore: 'Load more',
  feedKudos: 'kudos',
  feedComments: 'comments',
  dashboardNoWorkoutsYet: 'No workouts yet',
  dashboardNoWorkoutsDesc: 'Log your first one to start building streaks and earning XP.',
  dashboardLogWorkout: 'Log Workout',
  dashboardStartWorkout: 'START WORKOUT',
  dashboardStartWorkoutAria: 'Start a new workout',
  recommendationsSuggestedForToday: 'Suggested for today',
  recommendationsStartThisWorkout: 'Start this workout',
  recommendationsNotNow: 'Not now',
  recommendationsStartThisWorkoutAria: 'Start the suggested workout',
  toastAchievementUnlocked: 'Achievement unlocked:',
  toastShare: 'Share',

  // ── Activities ──────────────────────────────────────────────────────────
  activitiesTitle: 'Activities',
  activitiesTotalWorkouts: 'total workouts logged',
  activitiesSearchPlaceholder: 'Search workouts…',
  activitiesSearchAria: 'Search workouts by title or sport',
  activitiesAllSports: 'All Sports',
  activitiesSortBy: 'Sort:',
  activitiesNoWorkoutsYet: 'No workouts yet',
  activitiesNoWorkoutsFound: 'No workouts found',
  activitiesEmptyDescNone: 'Your logged sessions will appear here. Start with one — every streak begins with a single workout.',
  activitiesEmptyDescFilter: 'Nothing matches your filters. Try a different sport or search, or log a new workout.',
  activitiesClearFilters: 'Clear filters',
  activitiesWorkoutDeleted: 'Workout deleted',
  activitiesFailedDelete: 'Failed to delete workout',
  activitiesDeleteTitle: 'Delete Workout?',
  activitiesDeleteDesc: 'This will permanently delete this workout and deduct the XP earned. This cannot be undone.',
  activitiesDelete: 'Delete',
  activitiesLoadMore: 'Load more',
  activitiesRemaining: 'remaining',
  activitiesFilterBy: 'Filter by',
  activitiesSortActivitiesBy: 'Sort activities by',
  activitiesViewActivity: 'View activity',
  activitiesActivityDetail: 'Activity details',
  activitiesRouteMap: 'Route map',
  activitiesMapLoading: 'Loading map…',
  kudosAdd: 'Like this activity',
  kudosRemove: 'Unlike this activity',
  kudosYouLiked: 'You liked this',
  kudosCount: 'likes',
  commentsTitle: 'Comments',
  commentsCount: 'comments',
  commentsEmpty: 'No comments yet.',
  commentsPlaceholder: 'Add a comment…',
  commentsAdd: 'Add comment',
  commentsPost: 'Post',
  commentsDelete: 'Delete comment',

  // ── Progress ───────────────────────────────────────────────────────────
  progressTitle: 'Progress',
  progressSubtitle: 'Your fitness journey at a glance',
  progressWorkouts: 'Workouts',
  progressMiles: 'Miles',
  progressHours: 'Hours',
  progressLbsLifted: 'lbs Lifted',
  progressEmptyTitle: 'Your progress starts with your first workout',
  progressEmptyDesc: "Once you log runs, rides, swims, or lifts, you'll see personal records, level growth, and achievements here.",
  progressXpTotal: 'XP total',
  progressXpTo: 'XP to',
  progressToNextLevel: '% to next level',
  progressLevelProgression: 'Level Progression',
  progressPersonalRecords: 'Personal Records',
  progressAllTimeBests: 'All-time bests',
  progressFastestMile: 'Fastest Mile',
  progressLongestRun: 'Longest Run',
  progressLongestRide: 'Longest Ride',
  progressLongestSwim: 'Longest Swim',
  progressHeaviestLift: 'Heaviest Lift',
  progressNotYetRecorded: 'Not yet recorded',
  progressAchievements: 'Achievements',
  progressUnlocked: 'unlocked',
  progressEarned: 'Earned',
  progressLocked: 'Locked',
  progressStrengthTitle: 'Strength',
  progressStrengthSubtitle: 'Estimated 1RM by exercise',
  progress1RMNotYet: 'Log lifts to see estimated 1RM here',

  // ── Challenges ──────────────────────────────────────────────────────────
  challengesTitle: 'Challenges',
  challengesSubtitle: 'Push your limits and earn XP',
  challengesCreate: 'Create Challenge',
  challengesWeekly: 'Weekly Challenges',
  challengesMyChallenges: 'My Challenges',
  challengesAllSports: 'All Sports',
  challengesEmptyWeeklyTitle: 'No weekly challenges for this sport',
  challengesEmptyWeeklyDesc: 'Switch to another sport to see available weekly challenges, or try "All Sports."',
  challengesShowAllSports: 'Show All Sports',
  challengesEmptyCustomTitle: 'No custom challenges yet',
  challengesEmptyCustomDesc: "Set your own target and deadline — we'll track your progress and you'll earn XP when you complete it.",
  challengesEmptyCustomFilterTitle: 'No custom challenges for this sport',
  challengesEmptyCustomFilterDesc: 'Switch your sport filter to view other challenges.',
  challengesModalTitle: 'Create Challenge',
  challengesChallengeName: 'Challenge Name *',
  challengesType: 'Type',
  challengesSport: 'Sport',
  challengesTarget: 'Target',
  challengesXpReward: 'XP Reward',
  challengesDeadline: 'Deadline *',
  challengesPlaceholderName: 'e.g. Run 50 Miles in March',
  challengesPlaceholderTarget: '50',
  challengesTypeDistance: 'Distance',
  challengesTypeFrequency: 'Workout Count',
  challengesTypeDuration: 'Total Time',
  challengesWorkouts: 'workouts',
  challengesMinutes: 'minutes',
  challengesCreateButton: 'Create Challenge',
  challengesCloseModal: 'Close modal',
  challengesFillRequired: 'Please fill in all required fields',
  challengesCreated: 'Challenge created! 🎯',
  challengesCreateFailed: 'Failed to create challenge',
  challengesDeleted: 'Challenge deleted',
  challengesDeleteFailed: 'Failed to delete challenge',
  challengesDone: '✓ DONE',
  challengesCommunity: 'Community Challenge',

  // ── Leaderboard ────────────────────────────────────────────────────────
  leaderboardTitle: 'Leaderboard',
  leaderboardLoading: 'Loading…',
  leaderboardYourRank: 'Your rank:',
  leaderboardOf: 'of',
  leaderboardAmongFriends: 'among friends',
  leaderboardGlobal: 'Global',
  leaderboardFriends: 'Friends',
  leaderboardTotalXp: 'Total XP',
  leaderboardWeeklyDistance: 'Weekly Distance',
  leaderboardMonthlyVolume: 'Monthly Volume',
  leaderboardStreak: 'Streak',
  leaderboardEmptyTitle: "You're the first on the board",
  leaderboardEmptyDesc: "Keep logging workouts to build your XP and level. When others join, you'll see how you stack up.",
  leaderboardBackToDashboard: 'Back to Dashboard',
  leaderboardYou: 'You',

  // ── Profile ─────────────────────────────────────────────────────────────
  profileTitle: 'Profile',
  profileEditProfile: 'Edit Profile',
  profileLogOut: 'Log Out',
  profileAthlete: 'Athlete',
  profileJoined: 'Joined',
  profileStats: 'Stats',
  profileBadges: 'Badges',
  profileHistory: 'History',
  profileSettings: 'Settings',
  profileTotalWorkouts: 'Total Workouts',
  profileTotalDistance: 'Total Distance',
  profileTotalTime: 'Total Time',
  profileTotalXp: 'Total XP',
  profileCurrentStreak: 'Current Streak',
  profileVolumeLifted: 'Volume Lifted',
  profileNoBadgesTitle: 'No badges yet',
  profileNoBadgesDesc: 'Unlock achievements by logging workouts, building streaks, and hitting distance or volume milestones.',
  profileNoHistoryTitle: 'No workouts logged yet',
  profileNoHistoryDesc: 'Your workout history will appear here once you start logging sessions.',
  profileEditProfileTitle: 'Edit Profile',
  profileDisplayName: 'Display Name',
  profileUsername: 'Username',
  profilePrimarySport: 'Primary Sport',
  profileSaveChanges: 'Save Changes',
  profilePlaceholderUsername: '@username',
  profileNameRequired: 'Name is required',
  profileUpdated: 'Profile updated! ✨',
  profileUpdateFailed: 'Failed to update profile',
  profileSettingsTitle: 'Settings',
  profileUnits: 'Units',
  profilePrivacy: 'Privacy',
  profileNotifications: 'Notifications',
  profileImperial: 'Imperial (mi, lbs)',
  profileMetric: 'Metric (km, kg)',
  profilePublic: 'Public',
  profileFriendsOnly: 'Friends Only',
  profilePrivate: 'Private',
  profileCloseModal: 'Close modal',

  // ── Activity privacy (Strava-style) ─────────────────────────────────────
  privacyActivityVisibility: 'Default activity visibility',
  privacyVisibilityPublic: 'Public',
  privacyVisibilityFollowers: 'Followers only',
  privacyVisibilityPrivate: 'Private',
  privacyHideMapByDefault: 'Hide map by default',
  privacyHideStartTimeByDefault: 'Hide start time by default',
  privacyDateHidden: 'Date hidden',
  addActivityVisibility: 'Who can see this',
  addActivityHideMap: 'Hide map',
  addActivityHideStartTime: 'Hide start time',
  activityDetailPrivacy: 'Privacy',
  activityDetailEditPrivacy: 'Edit privacy',
  profileFollow: 'Follow',
  profileUnfollow: 'Unfollow',
  profileFollowers: 'Followers',
  profileFollowing: 'Following',
  profileFindPeople: 'Find people',
  socialFollowersListTitle: 'Followers',
  socialFollowingListTitle: 'Following',
  socialNoFollowers: 'No followers yet',
  socialNoFollowing: 'Not following anyone yet',
  socialViewProfile: 'View profile',

  // ── AddActivityModal ──────────────────────────────────────────────────
  addActivityLogWorkout: 'Log Workout',
  addActivityEditWorkout: 'Edit Workout',
  addActivityWorkoutLogged: 'Workout logged!',
  addActivityXpEarnedShare: 'XP earned. Share your progress?',
  addActivityPleaseTitle: 'Please enter a workout title',
  addActivityMustBeLoggedIn: 'You must be logged in to save workouts',
  addActivityEnterOneMetric: 'Enter at least one metric (duration, distance, or pace)',
  addActivityEnterDurationOrDistance: 'Enter either duration or distance',
  addActivityWorkoutUpdated: 'Workout updated! ✏️',
  addActivityXpDelayed: 'Workout logged, but XP update is delayed.',
  addActivityWorkoutLoggedXp: 'Workout logged!',
  addActivityPermissionError: 'Permission error while saving. Please re-login.',
  addActivityCouldNotSave: 'Could not save; check your connection.',
  addActivitySport: 'Sport',
  addActivityTitle: 'Title',
  addActivityDate: 'Date',
  addActivityDuration: 'Duration (min)',
  addActivityDurationOptional: 'Duration (min, optional)',
  addActivityDistance: 'Distance',
  addActivityAvgPace: 'Avg Pace (min/{unit}, optional)',
  addActivityDistanceYards: 'Distance (yards)',
  addActivityLapsOptional: 'Laps (optional)',
  addActivityPoolType: 'Pool Type',
  addActivityPool: 'Pool',
  addActivityOpenWater: 'Open Water',
  addActivityExercises: 'Exercises',
  addActivityTotalVolume: 'Total volume:',
  addActivityPlaceholderTitle: 'e.g. Morning Run',
  addActivityPlaceholderDuration: '45',
  addActivityPlaceholderDistance: '5.0',
  addActivityPlaceholderPace: '9.5',
  addActivityPlaceholderYards: '1500',
  addActivityPlaceholderLaps: '30',
  addActivityPlaceholderExercise: 'Exercise name (e.g. Bench Press)',
  addActivityPlaceholderReps: '10',
  addActivityPlaceholderWeight: '135',
  addActivityNotesOptional: 'Notes (optional)',
  addActivityPlaceholderNotes: 'How did it feel? Any PRs?',
  addActivitySet: 'Set',
  addActivityReps: 'Reps',
  addActivityWeightLbs: 'Weight (lbs)',
  addActivityAddSet: 'Add Set',
  addActivityAddExercise: 'Add Exercise',
  addActivityUpdateWorkout: 'Update Workout',
  addActivitySaving: 'Saving…',
  addActivitySelectSport: 'Select',
  addActivityCloseModal: 'Close modal',
  addActivityPrivacySection: 'Privacy',

  // ── GPS Recording (run/ride) ────────────────────────────────────────────
  gpsRecordWithGps: 'Record with GPS',
  gpsStartRecording: 'Start',
  gpsStopRecording: 'Stop',
  gpsRecording: 'Recording…',
  gpsPermissionDenied: 'Location permission was denied. Enable it in device settings to record with GPS.',
  gpsLocationUnavailable: 'Location is unavailable. Turn on location services and try again.',
  gpsErrorGeneric: 'Could not get location. Check permissions and try again.',
  gpsSummary: 'Recording summary',
  gpsSaveRecording: 'Save',
  gpsDiscardRecording: 'Discard',
  gpsDistance: 'Distance',
  gpsDuration: 'Duration',
  gpsPace: 'Pace',

  // ── Audio cues (GPS recording) ──────────────────────────────────────────
  audioCuesTitle: 'Audio cues',
  audioCuesDesc: 'Voice announcements during GPS recording (start, lap, stop).',
  audioCuesInterval: 'Lap announcement',
  audioCuesEveryHalfMile: 'Every 0.5 mi',
  audioCuesEvery1Mile: 'Every 1 mi',
  audioCuesEvery2Miles: 'Every 2 mi',
  audioCuesEvery5Min: 'Every 5 min',
  audioCuesEvery10Min: 'Every 10 min',

  // ── Exercise Library (AddActivityModal lift flow) ───────────────────────
  exerciseLibraryPickFromLibrary: 'Pick from library',
  exerciseLibrarySearchPlaceholder: 'Search exercises…',
  exerciseLibraryFilterByMuscle: 'Muscle group',
  exerciseLibraryAllMuscles: 'All',
  exerciseLibrarySelectExercise: 'Select exercise',
  exerciseLibraryOrTypeManually: 'Or type exercise name above',

  // ── Onboarding ─────────────────────────────────────────────────────────
  onboardingStep1Title: 'Track like a pro. Stay consistent.',
  onboardingStep1Body: 'Log workouts, build streaks, and level up. Zenith turns your effort into progress you can see — and rewards you for showing up.',
  onboardingGetStarted: 'Get started',
  onboardingStep2Title: "Quick setup — we'll personalize your experience",
  onboardingMainFocus: "What's your main focus?",
  onboardingMainGoal: "What's your main goal right now?",
  onboardingContinue: 'Continue',
  onboardingSkipForNow: 'Skip for now',
  onboardingStep3Title: "You're in. Time to move.",
  onboardingStep3Body: 'Your dashboard is ready. Log your first workout to start earning XP and building your streak.',
  onboardingLogFirstWorkout: 'Log my first workout',
  onboardingLoseWeight: 'Lose weight',
  onboardingBuildMuscle: 'Build muscle',
  onboardingStayActive: 'Stay active',

  // ── ErrorBoundary ───────────────────────────────────────────────────────
  errorBoundaryMessage: 'Something went wrong.',

  // ── OfflineIndicator ───────────────────────────────────────────────────
  offlineMessage: "You're offline",

  // ── Validation (AddActivityModal / generic) ─────────────────────────────
  validationMustBeNumber: 'must be a number.',
  validationCannotBeNegative: 'cannot be negative.',
  validationMustBeGreaterThanZero: 'must be greater than zero.',
  validationTooLarge: 'is too large (max',

  // ── Workout Templates ──────────────────────────────────────────────────
  templatesTitle: 'Workout Templates',
  templatesSubtitle: 'Save and reuse your lift structures',
  templatesEmptyTitle: 'No templates yet',
  templatesEmptyDesc: 'Create a template from a workout in Log Workout (Lift), or add one here.',
  templatesNewTemplate: 'New template',
  templatesStartFromTemplate: 'Start from template',
  templatesSaveAsTemplate: 'Save as template',
  templatesSelectTemplate: 'Select a template…',
  templatesTemplateName: 'Template name',
  templatesPlaceholderName: 'e.g. Push Day',
  templatesExercises: 'Exercises',
  templatesSetsCount: 'Sets',
  templatesAddExercise: 'Add exercise',
  templatesDeleteTemplate: 'Delete template',
  templatesDeleteConfirmTitle: 'Delete template?',
  templatesDeleteConfirmDesc: 'This template will be removed. Workouts already logged are not affected.',
  templatesCreated: 'Template saved',
  templatesUpdated: 'Template updated',
  templatesDeleted: 'Template deleted',
  templatesCreateFailed: 'Failed to save template',
  templatesNameRequired: 'Enter a template name',
  templatesOneExerciseRequired: 'Add at least one exercise',
  templatesEditTemplate: 'Edit template',

  // ── Rest Timer ───────────────────────────────────────────────────────
  restTimerTitle: 'Rest Timer',
  restTimerClose: 'Close rest timer',
  restTimerTimeRemaining: 'Time remaining',
  restTimerStart: 'Start',
  restTimerPause: 'Pause',
  restTimerReset: 'Reset',
  restTimerSoundOn: 'Sound when timer ends',
  restTimerVibrateOn: 'Vibrate when timer ends',
  restTimerOpen: 'Rest Timer',
  restTimerOpenAria: 'Open rest timer between sets',

  // ── Segments ───────────────────────────────────────────────────────────
  segmentsTitle: 'Segments',
  segmentsSubtitle: 'Create and compete on route segments',
  segmentsMySegments: 'My segments',
  segmentsAllSegments: 'All segments',
  segmentsEmptyTitle: 'No segments yet',
  segmentsEmptyDesc: 'Record a run or ride with GPS, then create a segment from that activity to start a leaderboard.',
  segmentsCreateFromActivity: 'Create segment from activity',
  segmentsLeaderboard: 'Leaderboard',
  segmentsBestTimes: 'Best times',
  segmentsSport: 'Sport',
  segmentsTime: 'Time',
  segmentsYouRanSegment: 'You ran this segment in',
  segmentsCreateSegment: 'Create segment',
  segmentsSegmentName: 'Segment name',
  segmentsStartDistance: 'Start (mi)',
  segmentsEndDistance: 'End (mi)',
  segmentsCreate: 'Create segment',
  segmentsCreated: 'Segment created',
  segmentsCreateFailed: 'Failed to create segment',
  segmentsNameRequired: 'Enter a segment name',
  segmentsInvalidRange: 'End distance must be greater than start distance.',
  segmentsBackToSegments: 'Back to segments',

  // ── Clubs ───────────────────────────────────────────────────────────────
  clubsTitle: 'Clubs',
  clubsSubtitle: 'Create and join clubs, see club feed and leaderboard',
  clubsMyClubs: 'My clubs',
  clubsDiscover: 'Discover clubs',
  clubsCreateClub: 'Create club',
  clubsCreateClubTitle: 'Create a club',
  clubsName: 'Club name',
  clubsDescription: 'Description',
  clubsNamePlaceholder: 'e.g. Weekend Runners',
  clubsDescriptionPlaceholder: 'What’s this club about?',
  clubsCreate: 'Create',
  clubsCreated: 'Club created',
  clubsCreateFailed: 'Failed to create club',
  clubsNameRequired: 'Enter a club name',
  clubsEmptyTitle: 'No clubs yet',
  clubsEmptyMyDesc: 'Create a club or discover and join one to see activities and leaderboards.',
  clubsEmptyDiscoverDesc: 'No public clubs to show. Create one and it will appear here for others.',
  clubsMembers: 'Members',
  clubsMemberCount: 'member',
  clubsMemberCountPlural: 'members',
  clubsFeed: 'Feed',
  clubsLeaderboard: 'Leaderboard',
  clubsJoin: 'Join',
  clubsLeave: 'Leave',
  clubsJoined: 'Joined',
  clubsLeft: 'Left club',
  clubsJoinFailed: 'Could not join club',
  clubsLeaveFailed: 'Could not leave club',
  clubsOwner: 'Owner',
  clubsBackToClubs: 'Back to clubs',
  clubsFeedEmpty: 'No activities from members yet.',
  clubsLeaderboardEmpty: 'No members with XP yet.',

  // ── Nutrition (Macros) ───────────────────────────────────────────────────
  nutritionTitle: 'Nutrition',
  nutritionSubtitle: 'Log daily macros and track your intake',
  nutritionDate: 'Date',
  nutritionLogEntry: 'Log entry',
  nutritionMealName: 'Meal or snack (optional)',
  nutritionMealNamePlaceholder: 'e.g. Breakfast, Lunch',
  nutritionProtein: 'Protein (g)',
  nutritionCarbs: 'Carbs (g)',
  nutritionFat: 'Fat (g)',
  nutritionCalories: 'Calories (optional)',
  nutritionAddEntry: 'Add entry',
  nutritionDailyTotals: 'Daily totals',
  nutritionProteinShort: 'P',
  nutritionCarbsShort: 'C',
  nutritionFatShort: 'F',
  nutritionCalShort: 'Cal',
  nutritionDailyGoal: 'Daily goal',
  nutritionSetGoal: 'Set goal',
  nutritionGoalProtein: 'Target protein (g)',
  nutritionGoalCarbs: 'Target carbs (g)',
  nutritionGoalFat: 'Target fat (g)',
  nutritionGoalCalories: 'Target calories',
  nutritionSaveGoal: 'Save goal',
  nutritionNoEntries: 'No entries yet',
  nutritionNoEntriesDesc: 'Add a meal or snack to start tracking your macros for this day.',
  nutritionEntryDeleted: 'Entry removed',
  nutritionSaveFailed: 'Could not save. Check your connection.',
  nutritionSaved: 'Entry saved',
  nutritionCloseModal: 'Close',
  nutritionEnterAtLeastOne: 'Enter at least one macro (protein, carbs, or fat).',
  nutritionGoalProgress: 'Goal progress',

  // ── Connect accounts (Strava, Apple Health) ───────────────────────────────
  connectTitle: 'Connect accounts',
  connectSubtitle: 'Import activities from Strava or Apple Health into Zenith.',
  connectStrava: 'Strava',
  connectStravaDesc: 'Import runs, rides, and other activities from your Strava account.',
  connectStravaConnect: 'Connect Strava',
  connectStravaImport: 'Import from Strava',
  connectStravaConnected: 'Connected',
  connectStravaDisconnect: 'Disconnect',
  connectStravaLastImport: 'Last import:',
  connectStravaNever: 'Never',
  connectAppleHealth: 'Apple Health',
  connectAppleHealthDesc: 'Import workouts from the Health app (iOS only).',
  connectAppleHealthImport: 'Import from Health',
  connectAppleHealthComingSoon: 'Coming soon',
  connectAppleHealthComingSoonDesc: 'Apple Health import is only available on iOS. Web and Android support may come later.',
  connectImporting: 'Importing…',
  connectImportDone: 'Import complete',
  connectImportResult: 'Imported {count} activities.',
  connectImportResultNone: 'No new activities to import.',
  connectImportFailed: 'Import failed',
  connectStravaNotConfigured: 'Strava is not configured. Add VITE_STRAVA_CLIENT_ID and deploy the exchangeStravaCode function.',
};
